imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@LombardBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    assets:
        packages:
            admingenerator_css:
              version: 1.0
              version_format: "%%1$s?v%%2$s"
            admingenerator_js:
              version: 1.0
              version_format: "%%1$s?v%%2$s"
            formextensions_css:
              version: 1.0
              version_format: "%%1$s?v%%2$s"
            formextensions_js:
              version: 1.0
              version_format: "%%1$s?v%%2$s"
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
#    bundles:        [] # comment this line to include all bundles by default
    filters:
        cssrewrite:
            apply_to: ["\.css$", "\.less$"]
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
          softdeleteable:
            class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
            enabled: true


admingenerator_generator:
    # choose and enable at least one
    use_propel:           false
    use_doctrine_orm:     true
    use_doctrine_odm:     false
    knp_menu_alias: admingen_sidebar
    # add this line if you want to use assetic
    base_admin_template: ::base.html.twig
    twig:
        use_localized_date: true
        date_format: 'yyyy-MM-dd'
        datetime_format: 'yyyy-MM-dd HH:mm'
        localized_date_format: "medium"
        localized_datetime_format: "medium"
        number_format:
            decimal: 2
            decimal_point: ','
            thousand_separator: ' '
    form_types:
      doctrine_orm:
    #   datetime: Admingenerator\FormExtensionsBundle\Form\Type\DateTimePickerType
    #    date:  Admingenerator\FormExtensionsBundle\Form\Type\DatePickerType
        entity: Admingenerator\FormExtensionsBundle\Form\Type\Select2EntityType
        choice: Admingenerator\FormExtensionsBundle\Form\Type\Select2ChoiceType
    filter_types:
      doctrine_orm:
    #   datetime: Admingenerator\FormExtensionsBundle\Form\Type\DateTimePickerType
    #    date:  Admingenerator\FormExtensionsBundle\Form\Type\DatePickerType
        entity: Admingenerator\FormExtensionsBundle\Form\Type\Select2EntityType
        choice: Admingenerator\FormExtensionsBundle\Form\Type\Select2ChoiceType
        
admingenerator_form_extensions:
    include_blueimp: true
    include_momentjs: true
    include_jqueryui: true
        
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: AdmingeneratorGeneratorBundle:KnpMenu:knp_menu_trans.html.twig

    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


stof_doctrine_extensions:
    default_locale: en_EN
    orm:
        default:
            # Activate the extensions you want
            timestampable:          true
            blameable:              true
            softdeleteable:         true        

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: AdmingeneratorGeneratorBundle:KnpMenu:knp_menu_trans.html.twig

    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

services:
  common.menu_builder:
    class: LombardBundle\Menu\MenuBuilder
    arguments:
      - "@knp_menu.factory"
      - "@request_stack"
      - 'LombardBundle_Deposit_list'
    tags:
      - { name: "knp_menu.menu_builder", method: "sidebarMenu", alias: "admingen_sidebar"}

            

